### ISSUE TITLE
run time

### ISSUE THREAD

**Issue by mishugeb** [danro9685/SparseSignatures#10]
I am doing an analysis with 21 Samples. It finished only 50 out of 500 cv repetitions with the following parameters in the last two days in an Intel(R) Xeon(R) Gold 6132 CPU @ 2.60GHz
machine with 28 processors. I can see 27 processors are working in parallel using the TOP command. I presume it might take weeks to extract 2-10 signatures from only 21 samples with the parameters I am using currently. But, In the future, I need to extract up to 45 signatures from 3000 samples which could be even slower. So do you think I am using good parameters for the nmf.LassoCV function (see below). Do you think that I should change some the of the parameters to get faster but accurate results?

**I have used the following parameters for the nmf.LassoCV function.** 
nmf_runs = 100 
iterations = 20 
cross_validation_iterations = 5 
cross_validation_repetitions  = 500 
lamda_values = c(0.01, 0.1)

**R version: 3.4.0**

**The CPU model I am using:**

**Operating system: Linux**

**Comment by danro9685** [comment]
Dear @mishugeb, 

I would advice you to split the cross validations into multiple independent processes rather then using all the cores (28 processes) for the 500 runs. 

The parallelization can get slower because of memory copies with lots of cross validations to be saved into RAM. So rather then doing all the 500 cross validations, maybe split it in let's say 10 or 20 batches of 50 or 25 cross validations iterations each. 

Also as a note, I am currently working at a faster implementation of SparseSignatures. You can contact me at daniele.ramazzotti1@gmail.com if in the future you need to run the method on a bigger set and I will let you know if the new implementation is ready. 

Best, 
Daniele
